### ISSUE TITLE
Wondertrade server crash

### ISSUE THREAD

**Issue by nicholasrobertm** [EnvyWare/WonderTrade-Forge#10]
```
    java.lang.ArrayIndexOutOfBoundsException: -1
        at com.envyful.wonder.trade.forge.ui.PokemonSelectUI.lambda$null$1(PokemonSelectUI.java:111)
        at com.envyful.wonder.trade.forge.shade.envy.api.forge.concurrency.listener.ServerTickListener.onServerTick(ServerTickListener.java:29)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_481_ServerTickListener_onServerTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:756)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:706)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:279)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)```

**Comment by danorris709** [comment]
Fixed in next release
