### ISSUE TITLE
help

### ISSUE THREAD

**Issue by StrictMaple** [EnvyWare/WonderTrade-Forge#12]
[04:15:06 WARN]: Exception in thread "pool-2-thread-2"
[04:15:06 WARN]: java.lang.NullPointerException
[04:15:06 WARN]:        at com.envyful.wonder.trade.forge.data.WonderTradeAttribute.load(WonderTradeAttribute.java:65)
[04:15:06 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.forge.player.ForgePlayerManager$PlayerListener.lambda$onPlayerJoin$0(ForgePlayerManager.java:112)
[04:15:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[04:15:06 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[04:15:06 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:15:22 WARN]: [pool-2-thread-1] ERROR com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool - WonderTrade - Exception during pool initialization.
[04:15:22 WARN]: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:15:22 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:633)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1014)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
[04:15:22 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[04:15:22 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:66)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:22)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.WonderTradeForge.lambda$onServerStarting$0(WonderTradeForge.java:58)
[04:15:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[04:15:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[04:15:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:15:22 WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[04:15:22 WARN]:        at java.net.SocketInputStream.socketRead0(Native Method)
[04:15:22 WARN]:        at java.net.SocketInputStream.socketRead(Unknown Source)
[04:15:22 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[04:15:22 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:568)
[04:15:22 WARN]:        ... 26 more
[04:15:22 WARN]: Exception in thread "pool-2-thread-1"
[04:15:22 WARN]: com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:596)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.checkFailFast(HikariPool.java:582)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.<init>(HikariPool.java:115)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:66)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.database.impl.SimpleHikariDatabase.<init>(SimpleHikariDatabase.java:22)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.WonderTradeForge.lambda$onServerStarting$0(WonderTradeForge.java:58)
[04:15:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[04:15:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[04:15:22 WARN]:        at java.lang.Thread.run(Unknown Source)
[04:15:22 WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:15:22 WARN]:        at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:990)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:633)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1014)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2190)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2221)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2016)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:776)
[04:15:22 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[04:15:22 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[04:15:22 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[04:15:22 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
[04:15:22 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:121)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.PoolBase.newConnection(PoolBase.java:364)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
[04:15:22 WARN]:        at com.envyful.wonder.trade.forge.shade.hikari.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
[04:15:22 WARN]:        ... 8 more
[04:15:22 WARN]: Caused by: java.net.SocketTimeoutException: Read timed out
[04:15:22 WARN]:        at java.net.SocketInputStream.socketRead0(Native Method)
[04:15:22 WARN]:        at java.net.SocketInputStream.socketRead(Unknown Source)
[04:15:22 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[04:15:22 WARN]:        at java.net.SocketInputStream.read(Unknown Source)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.fill(ReadAheadInputStream.java:101)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.readFromUnderlyingStreamIfNecessary(ReadAheadInputStream.java:144)
[04:15:22 WARN]:        at com.mysql.jdbc.util.ReadAheadInputStream.read(ReadAheadInputStream.java:174)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readFully(MysqlIO.java:3011)
[04:15:22 WARN]:        at com.mysql.jdbc.MysqlIO.readPacket(MysqlIO.java:568)
[04:15:22 WARN]:        ... 26 more

**Comment by danorris709** [comment]
Your config is wrong

**Comment by StrictMaple** [comment]
How to set the config

**Comment by StrictMaple** [comment]
broadcast-settings:
    always-broadcast: true
    broadcast-legends: true
    broadcast-ultra-beasts: true
    broadcast-shinies: true
default-generator-settings:
    blocked-types:
    - Hoopa
    blocked-specs:
    - hoopa
    allow-legends: true
    allow-ultra-beasts: true
    shiny-chance: 0.05
database-details:
    pool-name: WonderTrade
    ip: 0.0.0.0
    port: 6325
    username: admin
    password: password
    database: WonderTrade
    max-pool-size: 30
admin-u-i:
    gui-settings:
        title: WonderTrade
        height: 6
        fill-type: BLOCK
        filler-items:
            one:
                enabled: true
                type: minecraft:stained_glass_pane
                amount: 1
                damage: 15
                name: ' '
                lore: []
                nbt: {}
    page-positions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    next-page-button:
        x-pos: 8
        y-pos: 5
        enabled: true
        type: pixelmon:trade_holder_right
        amount: 1
        damage: 0
        name: '&aNext Page'
        lore: []
        nbt: {}
    previous-page-button:
        x-pos: 0
        y-pos: 5
        enabled: true
        type: pixelmon:trade_holder_left
        amount: 1
        damage: 0
        name: '&aPrevious Page'
        lore: []
        nbt: {}
    sprites:
        name: '&b%species_name% %nickname%'
        lore:
        - '&7Level: &b%level%'
        - '&7Shiny: &b%shiny%'
        - '&7Gender: %gender%'
        - '&7Breedable: %breedable%'
        - '&7Friendship: %friendship%'
        - '&7Nature: &b%nature%'
        - '&7Form: &b%form%'
        - '&7Growth: &b%size%'
        - '&7Ability: &b%ability%'
        - '&7Friendship: &b%friendship%'
        - '&7Untradeable: &b%untradeable%'
        - '&7Custom Texture: &b%custom_texture%'
        - ' '
        - '&7IVs (&b%iv_percentage%%&7):'
        - '    §7HP: %iv_hp% §d| §7Atk: %iv_attack% §d| §7Def: %iv_defence%'
        - '    §7SAtk: %iv_spattack% §d| §7SDef: %iv_spdefence% §d| §7Spd: %iv_speed%'
        - ' '
        - '&7EVs:'
        - '    §7HP: &b%ev_hp% §d| §7Atk: &b%ev_attack% §d| §7Def: &b%ev_defence%'
        - '    §7SAtk: &b%ev_spattack% §d| §7SDef: &b%ev_spdefence% §d| §7Spd: &b%ev_speed%'
        - ' '
        - '&7Moves:'
        - '    &b%move_1%'
        - '    &b%move_2%'
        - '    &b%move_3%'
        - '    &b%move_4%'
        - ' '
        - '%mew_cloned%'
        - '%trio_gemmed%'
        untrdeable-true-format: '&aTRUE'
        untradeable-false-format: '&cFALSE'
        ability-format: '%ability_name% %ability_ha%'
        ha-format: '&7(&c&lHA&7)'
        male-format: '&bMale'
        female-format: '&dFemale'
        none-format: '&fNONE'
        shiny-true-format: '&aTRUE'
        shiny-false-format: '&cFALSE'
        unbreedable-true-format: '&aTRUE'
        unbreedable-false-format: '&cFALSE'
        mew-cloned-format: '&7Times Cloned: %cloned%'
        gemmed-format: '&7Gemmed: %gemmed%'
        nature-format: '%nature_name% %mint_nature%'
        mint-nature-format: '&7(%mint_nature_name%&7)'
        normal-iv-colour: '&b'
        hyper-iv-colour: '&e'
gui-settings:
    title: WonderTrade
    height: 5
    fill-type: BLOCK
    filler-items:
        one:
            enabled: true
            type: minecraft:stained_glass_pane
            amount: 1
            damage: 15
            name: ' '
            lore: []
            nbt: {}
level-too-low-item:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 14
    name: '&c&lLevel too low'
    lore: []
    nbt: {}
untradeable-item:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 14
    name: '&c&lUntradeable'
    lore: []
    nbt: {}
click-to-confirm-button:
    enabled: true
    type: minecraft:stained_glass_pane
    amount: 1
    damage: 5
    name: '&a&lClick to confirm'
    lore: []
    nbt: {}
none-selected-item:
    x-pos: 5
    y-pos: 2
    enabled: true
    type: minecraft:barrier
    amount: 1
    damage: 0
    name: '&c&lNone selected'
    lore: []
    nbt: {}
sprite-config:
    name: '&b%species_name% %nickname%'
    lore:
    - '&7Level: &b%level%'
    - '&7Shiny: &b%shiny%'
    - '&7Gender: %gender%'
    - '&7Breedable: %breedable%'
    - '&7Friendship: %friendship%'
    - '&7Nature: &b%nature%'
    - '&7Form: &b%form%'
    - '&7Growth: &b%size%'
    - '&7Ability: &b%ability%'
    - '&7Friendship: &b%friendship%'
    - '&7Untradeable: &b%untradeable%'
    - '&7Custom Texture: &b%custom_texture%'
    - ' '
    - '&7IVs (&b%iv_percentage%%&7):'
    - '    §7HP: %iv_hp% §d| §7Atk: %iv_attack% §d| §7Def: %iv_defence%'
    - '    §7SAtk: %iv_spattack% §d| §7SDef: %iv_spdefence% §d| §7Spd: %iv_speed%'
    - ' '
    - '&7EVs:'
    - '    §7HP: &b%ev_hp% §d| §7Atk: &b%ev_attack% §d| §7Def: &b%ev_defence%'
    - '    §7SAtk: &b%ev_spattack% §d| §7SDef: &b%ev_spdefence% §d| §7Spd: &b%ev_speed%'
    - ' '
    - '&7Moves:'
    - '    &b%move_1%'
    - '    &b%move_2%'
    - '    &b%move_3%'
    - '    &b%move_4%'
    - ' '
    - '%mew_cloned%'
    - '%trio_gemmed%'
    untrdeable-true-format: '&aTRUE'
    untradeable-false-format: '&cFALSE'
    ability-format: '%ability_name% %ability_ha%'
    ha-format: '&7(&c&lHA&7)'
    male-format: '&bMale'
    female-format: '&dFemale'
    none-format: '&fNONE'
    shiny-true-format: '&aTRUE'
    shiny-false-format: '&cFALSE'
    unbreedable-true-format: '&aTRUE'
    unbreedable-false-format: '&cFALSE'
    mew-cloned-format: '&7Times Cloned: %cloned%'
    gemmed-format: '&7Gemmed: %gemmed%'
    nature-format: '%nature_name% %mint_nature%'
    mint-nature-format: '&7(%mint_nature_name%&7)'
    normal-iv-colour: '&b'
    hyper-iv-colour: '&e'
cooldown-seconds: 3600
min-required-level: 30
number-in-pool: 30
selected-sprite-pos: 23
persistent-pool: true
disable-u-i: false

**Comment by danorris709** [comment]
Find the correct database details
