### ISSUE TITLE
warnings when start the server

### ISSUE THREAD

**Issue by rafaelribe** [EnvyWare/WonderTrade-Forge#13]
Exception in thread "pool-6-thread-3"
[14:11:03 WARN]: java.lang.NullPointerException
[14:11:03 WARN]:        at com.envyful.better.dex.rewards.forge.player.DexRewardsAttribute.load(DexRewardsAttribute.java:65)
[14:11:03 WARN]:        at com.envyful.npc.storage.forge.shade.envy.api.player.save.impl.EmptySaveManager.loadData(EmptySaveManager.java:37)
[14:11:03 WARN]:        at com.envyful.npc.storage.forge.shade.envy.api.forge.player.ForgePlayerManager$PlayerListener.lambda$onPlayerJoin$0(ForgePlayerManager.java:108)
[14:11:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:11:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:11:03 WARN]:        at java.lang.Thread.run(Unknown Source)
[14:11:03 WARN]: Exception in thread "pool-3-thread-3"
[14:11:03 WARN]: java.lang.NullPointerException
[14:11:03 WARN]:        at com.envyful.wonder.trade.forge.data.WonderTradeAttribute.load(WonderTradeAttribute.java:70)
[14:11:03 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.player.save.impl.EmptySaveManager.loadData(EmptySaveManager.java:37)
[14:11:03 WARN]:        at com.envyful.wonder.trade.forge.shade.envy.api.forge.player.ForgePlayerManager$PlayerListener.lambda$onPlayerJoin$0(ForgePlayerManager.java:108)
[14:11:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:11:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:11:03 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by danorris709** [comment]
This error is from DexRewards
