### ISSUE TITLE
Mod issue URL is incorrect in mods.tml

### ISSUE THREAD

**Issue by StrangeOne101** [EnvyWare/WonderTrade-Forge#33]
# Description
In the mods.toml file, the issue URL points towards `https://github.com/EnvyWare/BetterDexRewards/issues`

# Example crash report showcasing incorrect issue URL
```A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
-- MOD wondertrade --
Details:
	Mod File: WonderTrade-Forge-6.4.5-1.16.5.jar
	Failure message: WonderTrade Forge has class loading errors
		java.lang.UnsupportedClassVersionError: com/envyful/wonder/trade/forge/shade/envy/api/database/Database has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	Mod Version: 6.4.5
	Mod Issue URL: https://github.com/EnvyWare/BetterDexRewards/issues
	Exception message: java.lang.UnsupportedClassVersionError: com/envyful/wonder/trade/forge/shade/envy/api/database/Database has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
Stacktrace:
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[?:1.8.0_51] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51] {}
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51] {}```

**Comment by danorris709** [comment]
Fixed in latest
